export const mock = [
  {
    images: "/images/main/mock/dog2.jpg",

    desertionNo: "448567202501695",
    rfidCode: null,

    breedName: "믹스견",
    animalTypeName: "개",
    foundDate: "20251105",
    sex: "암컷",
    neuterStatus: "중성화 안 함",
    age: "2023(년생)",
    weight: "13.5(Kg)",
    status: "보호중",
    province: "경상남도",
    city: "창원시",
    noticeStartDate: "20251105",
    noticeEndDate: "20251117",
    shelterName: "창원동물보호센터",
    shelterTel: "055-225-5701",
    shelterAddress:
      "경상남도 창원시 성산구 공단로474번길 117 (상복동) 창원동물보호센터",
    specialMark:
      "목줄했던 흔적있음. 많이 마른편.오른쪽 뒷다리 발바닥패드 상처.",
    foundPlace: "마산회원구 내서읍 신감리 902",
    color: "옅은 황색",
    healthInfo: null,
    vaccination: null,
    healthCheck: null,
    personality: null,
  },
  {
    images: "../images/main/mock/dog3.jpg",

    desertionNo: "448567202501686",
    rfidCode: null,

    breedName: "믹스견",
    animalTypeName: "개",
    foundDate: "20251105",
    sex: "암컷",
    neuterStatus: "중성화 안 함",
    age: "2023(년생)",
    weight: "13.5(Kg)",
    status: "보호중",
    province: "경상남도",
    city: "창원시",
    noticeStartDate: "20251105",
    noticeEndDate: "20251117",
    shelterName: "창원동물보호센터",
    shelterTel: "055-225-5701",
    shelterAddress:
      "경상남도 창원시 성산구 공단로474번길 117 (상복동) 창원동물보호센터",
    specialMark:
      "목줄했던 흔적있음. 많이 마른편.오른쪽 뒷다리 발바닥패드 상처.",
    foundPlace: "마산회원구 내서읍 신감리 902",
    color: "옅은 황색",
    healthInfo: null,
    vaccination: null,
    healthCheck: null,
    personality: null,
  },
  {
    images: "../images/main/mock/dog1.jpg",
    breedName: "말티즈",
    noticeEndDate: "2025-11-10",
    desertionNo: "448567202501691", //보호번호
    breedName: "믹스견",
    animalTypeName: "개",
    foundDate: "20251105",
    sex: "암컷",
    neuterStatus: "중성화 안 함",
    age: "2023(년생)",
    weight: "13.5(Kg)",
    status: "보호중",
    province: "경상남도",
    city: "창원시",
    noticeStartDate: "20251105",
    noticeEndDate: "20251117",
    shelterName: "창원동물보호센터",
    shelterTel: "055-225-5701",
    shelterAddress:
      "경상남도 창원시 성산구 공단로474번길 117 (상복동) 창원동물보호센터",
    specialMark:
      "목줄했던 흔적있음. 많이 마른편.오른쪽 뒷다리 발바닥패드 상처.",
    foundPlace: "마산회원구 내서읍 신감리 902",
    color: "옅은 황색",
    healthInfo: null,
    vaccination: null,
    healthCheck: null,
    personality: null,
  },
  {
    images: "../images/main/mock/cat1.jpg",
    desertionNo: "448567202501680", //보호번호
    breedName: "믹스견",
    animalTypeName: "고양이",
    foundDate: "20251105",
    sex: "암컷",
    neuterStatus: "중성화 안 함",
    age: "2023(년생)",
    weight: "13.5(Kg)",
    status: "보호중",
    province: "경상남도",
    city: "창원시",
    noticeStartDate: "20251105",
    noticeEndDate: "20251117",
    shelterName: "창원동물보호센터",
    shelterTel: "055-225-5701",
    shelterAddress:
      "경상남도 창원시 성산구 공단로474번길 117 (상복동) 창원동물보호센터",
    specialMark:
      "목줄했던 흔적있음. 많이 마른편.오른쪽 뒷다리 발바닥패드 상처.",
    foundPlace: "마산회원구 내서읍 신감리 902",
    color: "옅은 황색",
    healthInfo: null,
    vaccination: null,
    healthCheck: null,
    personality: null,
  },
  {
    images: "../images/main/mock/cat2.jpg",
    desertionNo: "448567202501681", //보호번호
    breedName: "믹스견",
    animalTypeName: "고양이",
    foundDate: "20251105",
    sex: "암컷",
    neuterStatus: "중성화 안 함",
    age: "2023(년생)",
    weight: "13.5(Kg)",
    status: "보호중",
    province: "경상남도",
    city: "창원시",
    noticeStartDate: "20251105",
    noticeEndDate: "20251117",
    shelterName: "창원동물보호센터",
    shelterTel: "055-225-5701",
    shelterAddress:
      "경상남도 창원시 성산구 공단로474번길 117 (상복동) 창원동물보호센터",
    specialMark:
      "목줄했던 흔적있음. 많이 마른편.오른쪽 뒷다리 발바닥패드 상처.",
    foundPlace: "마산회원구 내서읍 신감리 902",
    color: "옅은 황색",
    healthInfo: null,
    vaccination: null,
    healthCheck: null,
    personality: null,
  },
  {
    images: "../images/main/mock/cat3.jpg",
    desertionNo: "448567202501682", //보호번호
    breedName: "믹스견",
    animalTypeName: "고양이",
    foundDate: "20251105",
    sex: "암컷",
    neuterStatus: "중성화 안 함",
    age: "2023(년생)",
    weight: "13.5(Kg)",
    status: "보호중",
    province: "경상남도",
    city: "창원시",
    noticeStartDate: "20251105",
    noticeEndDate: "20251117",
    shelterName: "창원동물보호센터",
    shelterTel: "055-225-5701",
    shelterAddress:
      "경상남도 창원시 성산구 공단로474번길 117 (상복동) 창원동물보호센터",
    specialMark:
      "목줄했던 흔적있음. 많이 마른편.오른쪽 뒷다리 발바닥패드 상처.",
    foundPlace: "마산회원구 내서읍 신감리 902",
    color: "옅은 황색",
    healthInfo: null,
    vaccination: null,
    healthCheck: null,
    personality: null,
  },
];
